apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
  namespace: preprod
  annotations:
      circleci.com/project-id: 4f641306-eff2-47f5-9efa-43fc08af406b
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: nicklovenspierrelouis/nick:preprod
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always